version: "3.6"

services:
    lottery-react:
        container_name: lottery-react
        image: nikolaik/python-nodejs:python3.5-nodejs10-alpine
        restart: always
        # env_file: .env
        ports:
            - 3000:3000
        volumes:
            - ./:/src
        working_dir: /src
        extra_hosts:
            - "host.docker.internal:host-gateway"
        command:
            - /bin/sh
            - -c
            - |
                npm i
                sleep 999999999
                npm run start